version: '3'
services:
  # Web client
  website:
    build: ./map-client
    volumes:
      - ./map-client:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3001:3000
    links:
      - api
    depends_on:
      - api
    environment:
      WAIT_HOSTS: mongo:27017
      # REACT_APP_POLLING_TIME: 30000

  # CRON
  cron:
    build: ./map-cron-job
    volumes:
      - ./map-cron-job:/usr/src/app
    ports:
      - "3004:3004"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      API_URL: 'http://api:3002'
      POLLING_TIME: 30000

  # MQTT
  mqtt:
    build: ./map-mqtt
    volumes:
      - ./map-mqtt:/usr/src/app
    ports:
      - "3003:3003"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      # MQTT_URL: 'mqtt://test.mosquitto.org'
      MQTT_URL: tcp://202.44.44.232:1883
      WAIT_HOSTS: mongo:27017
      API_URL: http://api:3002

  # API
  api:
    build: ./map-server
    volumes:
      - ./map-server:/usr/src/app
    ports:
      - "3002:3002"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      DB_URI: mongodb://mongo:27017
      DB_NAME: map_app
      COLLECTION_SENSORS: sensors
      COLLECTION_EVENTS: events
      COLLECTION_WATCHER: watcher
      THRESHOLD: 60
      WAIT_HOSTS: mongo:27017
  
  # MongoDB sidecar
  mongo:
    image: mongo
    volumes:
      - ./map-db-mongo/data-volume:/data/db
    ports:
      - "27017:27017"
